//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconomizeMais
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProdutos()
        {
            this.tbPromocao = new HashSet<tbPromocao>();
            this.tbTop30 = new HashSet<tbTop30>();
        }
    
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public short FabricanteId { get; set; }
        public Nullable<int> Estoque { get; set; }
        public decimal Preco { get; set; }
        public byte[] Imagem { get; set; }
        public string ImagemTipo { get; set; }
    
        public virtual tbFabricante tbFabricante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPromocao> tbPromocao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTop30> tbTop30 { get; set; }
    }
}
