//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconomizeMais
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTop30
    {
        public int estab { get; set; }
        public string produto { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fim { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> promocao { get; set; }
        public Nullable<byte> item_top { get; set; }
    
        public virtual tbEstab tbEstab { get; set; }
        public virtual tbProdutos tbProdutos { get; set; }
    }
}
