//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconomizeMais
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbWebMixariaEntities : DbContext
    {
        public dbWebMixariaEntities()
            : base("name=dbWebMixariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbEstab> tbEstab { get; set; }
        public virtual DbSet<tbFabricante> tbFabricante { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipio { get; set; }
        public virtual DbSet<tbPromocao> tbPromocao { get; set; }
        public virtual DbSet<tbTipoEst> tbTipoEst { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbProdutos> tbProdutos { get; set; }
        public virtual DbSet<tbTop30> tbTop30 { get; set; }
    }
}
