//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconomizeMais
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPromocao
    {
        public int Estab { get; set; }
        public string Produto { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public decimal Preco { get; set; }
        public decimal Promocao { get; set; }
        public Nullable<byte> Prioridade { get; set; }
    
        public virtual tbEstab tbEstab { get; set; }
        public virtual tbProdutos tbProdutos { get; set; }
    }
}
